//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.4.1-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\HP\documents\visual studio 2013\Projects\Testing\Testing\Testing.g4 by ANTLR 4.4.1-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace Testing {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ITestingListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.4.1-SNAPSHOT")]
[System.CLSCompliant(false)]
public partial class TestingBaseListener : ITestingListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.dropt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDropt([NotNull] TestingParser.DroptContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.dropt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDropt([NotNull] TestingParser.DroptContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStart([NotNull] TestingParser.StartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStart([NotNull] TestingParser.StartContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.tid1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTid1([NotNull] TestingParser.Tid1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.tid1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTid1([NotNull] TestingParser.Tid1Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.tid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTid([NotNull] TestingParser.TidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.tid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTid([NotNull] TestingParser.TidContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.sid1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSid1([NotNull] TestingParser.Sid1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.sid1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSid1([NotNull] TestingParser.Sid1Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.sid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSid([NotNull] TestingParser.SidContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.sid"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSid([NotNull] TestingParser.SidContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.inid21"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInid21([NotNull] TestingParser.Inid21Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.inid21"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInid21([NotNull] TestingParser.Inid21Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.inid2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInid2([NotNull] TestingParser.Inid2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.inid2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInid2([NotNull] TestingParser.Inid2Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.inum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInum([NotNull] TestingParser.InumContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.inum"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInum([NotNull] TestingParser.InumContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.inum1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInum1([NotNull] TestingParser.Inum1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.inum1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInum1([NotNull] TestingParser.Inum1Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.inid1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInid1([NotNull] TestingParser.Inid1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.inid1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInid1([NotNull] TestingParser.Inid1Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.selstart3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelstart3([NotNull] TestingParser.Selstart3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.selstart3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelstart3([NotNull] TestingParser.Selstart3Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.selstart2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelstart2([NotNull] TestingParser.Selstart2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.selstart2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelstart2([NotNull] TestingParser.Selstart2Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.selstart1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelstart1([NotNull] TestingParser.Selstart1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.selstart1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelstart1([NotNull] TestingParser.Selstart1Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.selwarn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelwarn([NotNull] TestingParser.SelwarnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.selwarn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelwarn([NotNull] TestingParser.SelwarnContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.iddf3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIddf3([NotNull] TestingParser.Iddf3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.iddf3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIddf3([NotNull] TestingParser.Iddf3Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idnc3c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdnc3c([NotNull] TestingParser.Idnc3cContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idnc3c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdnc3c([NotNull] TestingParser.Idnc3cContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idc23c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdc23c([NotNull] TestingParser.Idc23cContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idc23c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdc23c([NotNull] TestingParser.Idc23cContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idc13c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdc13c([NotNull] TestingParser.Idc13cContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idc13c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdc13c([NotNull] TestingParser.Idc13cContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.iddf1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIddf1([NotNull] TestingParser.Iddf1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.iddf1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIddf1([NotNull] TestingParser.Iddf1Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idc23a"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdc23a([NotNull] TestingParser.Idc23aContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idc23a"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdc23a([NotNull] TestingParser.Idc23aContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.iddf2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIddf2([NotNull] TestingParser.Iddf2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.iddf2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIddf2([NotNull] TestingParser.Iddf2Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idc13a"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdc13a([NotNull] TestingParser.Idc13aContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idc13a"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdc13a([NotNull] TestingParser.Idc13aContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idch3c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdch3c([NotNull] TestingParser.Idch3cContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idch3c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdch3c([NotNull] TestingParser.Idch3cContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.ridnc2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRidnc2([NotNull] TestingParser.Ridnc2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.ridnc2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRidnc2([NotNull] TestingParser.Ridnc2Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.ridnc1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRidnc1([NotNull] TestingParser.Ridnc1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.ridnc1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRidnc1([NotNull] TestingParser.Ridnc1Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idc21"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdc21([NotNull] TestingParser.Idc21Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idc21"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdc21([NotNull] TestingParser.Idc21Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idch3a"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdch3a([NotNull] TestingParser.Idch3aContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idch3a"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdch3a([NotNull] TestingParser.Idch3aContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.iddf2c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIddf2c([NotNull] TestingParser.Iddf2cContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.iddf2c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIddf2c([NotNull] TestingParser.Iddf2cContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idnc2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdnc2([NotNull] TestingParser.Idnc2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idnc2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdnc2([NotNull] TestingParser.Idnc2Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.ridnc2c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRidnc2c([NotNull] TestingParser.Ridnc2cContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.ridnc2c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRidnc2c([NotNull] TestingParser.Ridnc2cContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idnc3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdnc3([NotNull] TestingParser.Idnc3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idnc3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdnc3([NotNull] TestingParser.Idnc3Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idchc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdchc([NotNull] TestingParser.IdchcContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idchc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdchc([NotNull] TestingParser.IdchcContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idnc1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdnc1([NotNull] TestingParser.Idnc1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idnc1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdnc1([NotNull] TestingParser.Idnc1Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idc22"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdc22([NotNull] TestingParser.Idc22Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idc22"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdc22([NotNull] TestingParser.Idc22Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idc23"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdc23([NotNull] TestingParser.Idc23Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idc23"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdc23([NotNull] TestingParser.Idc23Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idnc2c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdnc2c([NotNull] TestingParser.Idnc2cContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idnc2c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdnc2c([NotNull] TestingParser.Idnc2cContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idc22c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdc22c([NotNull] TestingParser.Idc22cContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idc22c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdc22c([NotNull] TestingParser.Idc22cContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idc12c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdc12c([NotNull] TestingParser.Idc12cContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idc12c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdc12c([NotNull] TestingParser.Idc12cContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idcht1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdcht1([NotNull] TestingParser.Idcht1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idcht1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdcht1([NotNull] TestingParser.Idcht1Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idcht3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdcht3([NotNull] TestingParser.Idcht3Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idcht3"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdcht3([NotNull] TestingParser.Idcht3Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.iddf3c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIddf3c([NotNull] TestingParser.Iddf3cContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.iddf3c"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIddf3c([NotNull] TestingParser.Iddf3cContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdch([NotNull] TestingParser.IdchContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idch"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdch([NotNull] TestingParser.IdchContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.iddf3a"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIddf3a([NotNull] TestingParser.Iddf3aContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.iddf3a"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIddf3a([NotNull] TestingParser.Iddf3aContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idc13"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdc13([NotNull] TestingParser.Idc13Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idc13"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdc13([NotNull] TestingParser.Idc13Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idc11"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdc11([NotNull] TestingParser.Idc11Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idc11"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdc11([NotNull] TestingParser.Idc11Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idnc3a"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdnc3a([NotNull] TestingParser.Idnc3aContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idnc3a"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdnc3a([NotNull] TestingParser.Idnc3aContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.idc12"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdc12([NotNull] TestingParser.Idc12Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.idc12"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdc12([NotNull] TestingParser.Idc12Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.selsec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelsec([NotNull] TestingParser.SelsecContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.selsec"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelsec([NotNull] TestingParser.SelsecContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.instart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstart([NotNull] TestingParser.InstartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.instart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstart([NotNull] TestingParser.InstartContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.gram"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGram([NotNull] TestingParser.GramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.gram"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGram([NotNull] TestingParser.GramContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.startc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStartc([NotNull] TestingParser.StartcContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.startc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStartc([NotNull] TestingParser.StartcContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInit([NotNull] TestingParser.InitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.init"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInit([NotNull] TestingParser.InitContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.drop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDrop([NotNull] TestingParser.DropContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.drop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDrop([NotNull] TestingParser.DropContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExp([NotNull] TestingParser.ExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.exp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExp([NotNull] TestingParser.ExpContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.sel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSel([NotNull] TestingParser.SelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.sel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSel([NotNull] TestingParser.SelContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.selexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelexp([NotNull] TestingParser.SelexpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.selexp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelexp([NotNull] TestingParser.SelexpContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.colsel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColsel([NotNull] TestingParser.ColselContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.colsel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColsel([NotNull] TestingParser.ColselContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.tabsel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTabsel([NotNull] TestingParser.TabselContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.tabsel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTabsel([NotNull] TestingParser.TabselContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.ins"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIns([NotNull] TestingParser.InsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.ins"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIns([NotNull] TestingParser.InsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.insexp1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInsexp1([NotNull] TestingParser.Insexp1Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.insexp1"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInsexp1([NotNull] TestingParser.Insexp1Context context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="TestingParser.insexp2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInsexp2([NotNull] TestingParser.Insexp2Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="TestingParser.insexp2"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInsexp2([NotNull] TestingParser.Insexp2Context context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Testing
