//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.4.1-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\HP\documents\visual studio 2013\Projects\Testing\Testing\Testing.g4 by ANTLR 4.4.1-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace Testing {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="TestingParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.4.1-SNAPSHOT")]
[System.CLSCompliant(false)]
public interface ITestingVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>dropt</c>
	/// labeled alternative in <see cref="TestingParser.drop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDropt([NotNull] TestingParser.DroptContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>start</c>
	/// labeled alternative in <see cref="TestingParser.init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStart([NotNull] TestingParser.StartContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>tid1</c>
	/// labeled alternative in <see cref="TestingParser.tabsel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTid1([NotNull] TestingParser.Tid1Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>tid</c>
	/// labeled alternative in <see cref="TestingParser.tabsel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTid([NotNull] TestingParser.TidContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>sid1</c>
	/// labeled alternative in <see cref="TestingParser.colsel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSid1([NotNull] TestingParser.Sid1Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>sid</c>
	/// labeled alternative in <see cref="TestingParser.colsel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSid([NotNull] TestingParser.SidContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>inid21</c>
	/// labeled alternative in <see cref="TestingParser.insexp2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInid21([NotNull] TestingParser.Inid21Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>inid2</c>
	/// labeled alternative in <see cref="TestingParser.insexp2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInid2([NotNull] TestingParser.Inid2Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>inum</c>
	/// labeled alternative in <see cref="TestingParser.insexp2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInum([NotNull] TestingParser.InumContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>inum1</c>
	/// labeled alternative in <see cref="TestingParser.insexp2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInum1([NotNull] TestingParser.Inum1Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>inid1</c>
	/// labeled alternative in <see cref="TestingParser.insexp1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInid1([NotNull] TestingParser.Inid1Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>selstart3</c>
	/// labeled alternative in <see cref="TestingParser.sel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelstart3([NotNull] TestingParser.Selstart3Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>selstart2</c>
	/// labeled alternative in <see cref="TestingParser.sel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelstart2([NotNull] TestingParser.Selstart2Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>selstart1</c>
	/// labeled alternative in <see cref="TestingParser.sel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelstart1([NotNull] TestingParser.Selstart1Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>selwarn</c>
	/// labeled alternative in <see cref="TestingParser.sel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelwarn([NotNull] TestingParser.SelwarnContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>iddf3</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIddf3([NotNull] TestingParser.Iddf3Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idnc3c</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdnc3c([NotNull] TestingParser.Idnc3cContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idc23c</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdc23c([NotNull] TestingParser.Idc23cContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idc13c</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdc13c([NotNull] TestingParser.Idc13cContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>iddf1</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIddf1([NotNull] TestingParser.Iddf1Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idc23a</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdc23a([NotNull] TestingParser.Idc23aContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>iddf2</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIddf2([NotNull] TestingParser.Iddf2Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idc13a</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdc13a([NotNull] TestingParser.Idc13aContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idch3c</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdch3c([NotNull] TestingParser.Idch3cContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ridnc2</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRidnc2([NotNull] TestingParser.Ridnc2Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ridnc1</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRidnc1([NotNull] TestingParser.Ridnc1Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idc21</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdc21([NotNull] TestingParser.Idc21Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idch3a</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdch3a([NotNull] TestingParser.Idch3aContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>iddf2c</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIddf2c([NotNull] TestingParser.Iddf2cContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idnc2</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdnc2([NotNull] TestingParser.Idnc2Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>ridnc2c</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRidnc2c([NotNull] TestingParser.Ridnc2cContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idnc3</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdnc3([NotNull] TestingParser.Idnc3Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idchc</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdchc([NotNull] TestingParser.IdchcContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idnc1</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdnc1([NotNull] TestingParser.Idnc1Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idc22</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdc22([NotNull] TestingParser.Idc22Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idc23</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdc23([NotNull] TestingParser.Idc23Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idnc2c</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdnc2c([NotNull] TestingParser.Idnc2cContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idc22c</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdc22c([NotNull] TestingParser.Idc22cContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idc12c</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdc12c([NotNull] TestingParser.Idc12cContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idcht1</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdcht1([NotNull] TestingParser.Idcht1Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idcht3</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdcht3([NotNull] TestingParser.Idcht3Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>iddf3c</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIddf3c([NotNull] TestingParser.Iddf3cContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idch</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdch([NotNull] TestingParser.IdchContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>iddf3a</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIddf3a([NotNull] TestingParser.Iddf3aContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idc13</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdc13([NotNull] TestingParser.Idc13Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idc11</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdc11([NotNull] TestingParser.Idc11Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idnc3a</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdnc3a([NotNull] TestingParser.Idnc3aContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>idc12</c>
	/// labeled alternative in <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdc12([NotNull] TestingParser.Idc12Context context);

	/// <summary>
	/// Visit a parse tree produced by the <c>selsec</c>
	/// labeled alternative in <see cref="TestingParser.selexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelsec([NotNull] TestingParser.SelsecContext context);

	/// <summary>
	/// Visit a parse tree produced by the <c>instart</c>
	/// labeled alternative in <see cref="TestingParser.ins"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstart([NotNull] TestingParser.InstartContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TestingParser.gram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGram([NotNull] TestingParser.GramContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TestingParser.startc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStartc([NotNull] TestingParser.StartcContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TestingParser.init"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInit([NotNull] TestingParser.InitContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TestingParser.drop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDrop([NotNull] TestingParser.DropContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TestingParser.exp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExp([NotNull] TestingParser.ExpContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TestingParser.sel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSel([NotNull] TestingParser.SelContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TestingParser.selexp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelexp([NotNull] TestingParser.SelexpContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TestingParser.colsel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColsel([NotNull] TestingParser.ColselContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TestingParser.tabsel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTabsel([NotNull] TestingParser.TabselContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TestingParser.ins"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIns([NotNull] TestingParser.InsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TestingParser.insexp1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsexp1([NotNull] TestingParser.Insexp1Context context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="TestingParser.insexp2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsexp2([NotNull] TestingParser.Insexp2Context context);
}
} // namespace Testing
